---
title: "ManyPrimates_Pilot_Data_Processing"
author: "Manuel Bohn"
date: "4 7 2018"
output: html_document
---
```{r}
library(tidyverse)
library(readxl)
```



```{r sample}
# sample file
sample <- read.csv(file="../data/raw_data/coding_sample.csv", sep = ";")
```

```{r kristiansand}

kris_raw <- read.csv(file="../data/raw_data/AlbaMotes_datakristiansand_ManyPrimates.csv", sep = ",")
# check column names
names(sample) %in%  names(kris_raw)
# check condition names
unique(sample$condition) %in%  unique(kris_raw$condition)

# check species
unique(kris_raw$species)
# check subject
unique(kris_raw$subject_site)
# check age
unique(kris_raw$age)
# check cup distance
unique(kris_raw$cup_distance)
# check task experience
unique(kris_raw$task_experience) %in% unique(sample$task_experience)
# check board size
unique(kris_raw$board_size)
# check test situation
unique(kris_raw$test_situation) %in% unique(sample$test_situation)
# check session
unique(kris_raw$session)
# check block
unique(kris_raw$block)
# check trial
unique(kris_raw$trial)
# check pick
unique(kris_raw$pick)
# check hiding locations
unique(kris_raw$hiding_location) %in% unique(sample$hiding_location)
# check correct
unique(kris_raw$correct)


# change data file
kris <- kris_raw %>%
  mutate(test_situation = as.factor(ifelse(test_situation == "solitary","single","group")),
         species = recode_factor(species,"black faced spider monkeys" = "black_faced_spider_monkey","ring tailed lemur" = "ring_tailed_lemur"))%>%
  filter(!is.na(pick))
```

```{r kumamoto}

kuma_raw <- read_excel("../data/raw_data/ManyPrimates Pilot Coding -kano.xlsx", 2)
# check column names
names(kuma_raw) == names(sample)
# check condition names
unique(sample$condition) == unique(kuma_raw$condition)

# check species
unique(kuma_raw$species)
# check subject
unique(kuma_raw$subject_site)
# check age
unique(kuma_raw$age)
# check cup distance
unique(kuma_raw$cup_distance)
# check task experience
unique(kuma_raw$task_experience) %in% unique(sample$task_experience)
# check board size
unique(kuma_raw$board_size)
# check test situation
unique(kuma_raw$test_situation) %in% unique(sample$test_situation)
# check session
unique(kuma_raw$session)
# check block
unique(kuma_raw$block)
# check trial
unique(kuma_raw$trial)
# check pick
unique(kuma_raw$pick)
# check hiding locations
unique(kuma_raw$hiding_location) %in% unique(sample$hiding_location)
# check correct
unique(kuma_raw$correct)

# change data file
kuma <- kuma_raw %>%
  select(-`Second Coder`) %>%
  mutate(condition = ifelse (condition == "0s","short",ifelse (condition == "15s","medium" ,"long")))%>%
  filter(!is.na(pick))
```

```{r edinburgh capuchins}

edin_cap_raw <- read_excel("../data/raw_data/ManyPrimates Pilot_CapuchinsEdi_Voelter.xlsx", 1)
# check column names
names(sample) %in%  names(edin_cap_raw)
# check condition names
unique(sample$condition) %in%  unique(edin_cap_raw$condition)

# check species
unique(edin_cap_raw$species)
# check subject
unique(edin_cap_raw$subject_site)
# check age
unique(edin_cap_raw$age)
# check cup distance
unique(edin_cap_raw$cup_distance)
# check task experience
unique(edin_cap_raw$task_experience) %in% unique(sample$task_experience)
# check board size
unique(edin_cap_raw$board_size)
# check test situation
unique(edin_cap_raw$test_situation) %in% unique(sample$test_situation)
# check session
unique(edin_cap_raw$session)
# check block
unique(edin_cap_raw$block)
# check trial
unique(edin_cap_raw$trial)
# check pick
unique(edin_cap_raw$pick)
# check hiding locations
unique(edin_cap_raw$hiding_location) %in% unique(sample$hiding_location)
# check correct
unique(edin_cap_raw$correct)

# change data file
edin_cap <- edin_cap_raw %>%
  mutate(researcher = "voelter")%>%
  filter(!is.na(pick))%>%
  mutate(session = as.numeric(session))%>%
  group_by(subject_site)%>%
  mutate(trial = 1:length(pick)) # to make trial a continous variable)
```

```{r sweetwaters chimps 1}
 
swee_1_raw <- read.csv(file="../data/raw_data/Data_sweetwaters.csv", sep = ";")
# check column names
names(sample) %in%  names(edin_cap_raw)
# check condition names
unique(sample$condition) %in%  unique(swee_1_raw$condition)

# check species
unique(swee_1_raw$species)
# check subject
unique(swee_1_raw$subject_site)
# check age
unique(swee_1_raw$age)
# check cup distance
unique(swee_1_raw$cup_distance)
# check task experience
unique(swee_1_raw$task_experience) %in% unique(sample$task_experience)
# check board size
unique(swee_1_raw$board_size)
# check test situation
unique(swee_1_raw$test_situation) %in% unique(sample$test_situation)
# check session
unique(swee_1_raw$session)
# check block
unique(swee_1_raw$block)
# check trial
unique(swee_1_raw$trial)
# check pick
unique(swee_1_raw$pick)
# check hiding locations
unique(swee_1_raw$hiding_location) %in% unique(sample$hiding_location)
# check correct
unique(swee_1_raw$correct)

# change data file
swee_1 <- swee_1_raw %>%
  mutate(researcher = "haux",
         species = "chimpanzee")%>%
  filter(!is.na(pick))
```

```{r sweetwaters chimps 2}
swee_2_raw <- read_excel("../data/raw_data/manyprimatespilot_sweetwaters_group2.xlsx", 1)
# check column names
names(sample) %in%  names(swee_2_raw)
# check condition names
unique(sample$condition) %in%  unique(swee_2_raw$condition)

# check species
unique(swee_2_raw$species)
# check subject
unique(swee_2_raw$subject_site)
# check age
unique(swee_2_raw$age)
# check cup distance
unique(swee_2_raw$cup_distance)
# check task experience
unique(swee_2_raw$task_experience) %in% unique(sample$task_experience)
# check board size
unique(swee_2_raw$board_size)
# check test situation
unique(swee_2_raw$test_situation) %in% unique(sample$test_situation)
# check session
unique(swee_2_raw$session)
# check block
unique(swee_2_raw$block)
# check trial
unique(swee_2_raw$trial)
# check pick
unique(swee_2_raw$pick)
# check hiding locations
unique(swee_2_raw$hiding_location) %in% unique(sample$hiding_location)
# check correct
unique(swee_2_raw$correct)

# change data file
swee_2 <- swee_2_raw %>%
  mutate(species = "chimpanzee",
         secondary_pick = as.character(secondary_pick))%>%
  filter(!is.na(pick))
```



```{r dpz lemurs}

dpz_lem_raw <- read_excel("../data/raw_data/data_ruffed_ringtailed_lemurs_C_Fichtel.xlsx", 1)
# check column names
names(sample) %in%  names(dpz_lem_raw)
# check condition names
unique(sample$condition) %in%  unique(dpz_lem_raw$condition)

# check species
unique(dpz_lem_raw$species)
# check subject
unique(dpz_lem_raw$subject_site)
# check age
unique(dpz_lem_raw$age)
# check cup distance
unique(dpz_lem_raw$cup_distance)
# check task experience
unique(dpz_lem_raw$task_experience) %in% unique(sample$task_experience)
# check board size
unique(dpz_lem_raw$board_size)
# check test situation
unique(dpz_lem_raw$test_situation) %in% unique(sample$test_situation)
# check session
unique(dpz_lem_raw$session)
# check block
unique(dpz_lem_raw$block)
# check trial
unique(dpz_lem_raw$trial)
# check pick
unique(dpz_lem_raw$pick)
# check hiding locations
unique(dpz_lem_raw$hiding_location) %in% unique(sample$hiding_location)
# check correct
unique(dpz_lem_raw$correct)

# change data file
dpz_lem <- dpz_lem_raw %>%
  mutate(condition = ifelse (condition == "0s","short",ifelse (condition == "15s","medium" ,"long")),
         species = recode_factor(species,"black-ad white ruffed lemur" = "black_and_white_ruffed_lemur","ring-tailed lemurs" = "ring_tailed_lemur"),
         cup_distance = gsub(" cm","",cup_distance),
         cup_distance = as.numeric(cup_distance),
         board_size = substr(board_size,1,2),
         board_size = as.numeric(board_size),
         date = gsub("-","",date),
         date = as.numeric(date))%>%
  filter(!is.na(pick))
```

```{r lincoln park zoo}

linc_raw <- read_excel("../data/raw_data/LPZ 3 cups data June 2018 Hopper Egelkamp Ross.xlsx", 1)
# check column names
names(sample) %in%  names(linc_raw)
# check condition names
unique(sample$condition) %in%  unique(linc_raw$condition)

# check species
unique(linc_raw$species)
# check subject
unique(linc_raw$subject_site)
# check age
unique(linc_raw$age)
# check cup distance
unique(linc_raw$cup_distance)
# check task experience
unique(linc_raw$task_experience) %in% unique(sample$task_experience)
# check board size
unique(linc_raw$board_size)
# check test situation
unique(linc_raw$test_situation) %in% unique(sample$test_situation)
# check session
unique(linc_raw$session)
# check block
unique(linc_raw$block)
# check trial
unique(linc_raw$trial)
# check pick
unique(linc_raw$pick)
# check hiding locations
unique(linc_raw$hiding_location) %in% unique(sample$hiding_location)
# check correct
unique(linc_raw$correct)

# change data file
linc <- linc_raw %>%
  mutate(species = recode_factor(species,"Gorilla" = "gorilla"),
         board_size = 61.5)%>%
  filter(!is.na(pick))
```

```{r dpz long tailed macaques}

dpz_mac_raw <- read_excel("../data/raw_data/ManyPrimates_data dpz_long-tailed macaques.xlsx", 1)
# check column names
names(sample) %in%  names(dpz_mac_raw)
# check condition names
unique(sample$condition) %in%  unique(dpz_mac_raw$condition)

# check species
unique(dpz_mac_raw$species)
# check subject
unique(dpz_mac_raw$subject_site)
# check age
unique(dpz_mac_raw$age)
# check cup distance
unique(dpz_mac_raw$cup_distance)
# check task experience
unique(dpz_mac_raw$task_experience) %in% unique(sample$task_experience)
# check board size
unique(dpz_mac_raw$board_size)
# check test situation
unique(dpz_mac_raw$test_situation) %in% unique(sample$test_situation)
# check session
unique(dpz_mac_raw$session)
# check block
unique(dpz_mac_raw$block)
# check trial
unique(dpz_mac_raw$trial)
# check pick
unique(dpz_mac_raw$pick)
# check hiding locations
unique(dpz_mac_raw$hiding_location) %in% unique(sample$hiding_location)
# check correct
unique(dpz_mac_raw$correct)

# change data file
dpz_mac <- dpz_mac_raw %>%
  mutate(species = recode_factor(species,"long-tailed macaque" = "long_tailed_macaque"),
         correct = as.numeric(correct),
         secondary_pick = as.character(secondary_pick))%>%
  filter(!is.na(pick))
```

```{r edinburgh squirel monkeys}

edin_squ_raw <- read_excel("../data/raw_data/ManyPrimates Pilot Coding_Squirrel monkeys_EW_17.7.18.xlsx", 1)
# check column names
names(sample) %in%  names(edin_squ_raw)
# check condition names
unique(sample$condition) %in%  unique(edin_squ_raw$condition)

# check species
unique(edin_squ_raw$species)
# check subject
unique(edin_squ_raw$subject_site)
# check age
unique(edin_squ_raw$age)
# check cup distance
unique(edin_squ_raw$cup_distance)
# check task experience
unique(edin_squ_raw$task_experience) %in% unique(sample$task_experience)
# check board size
unique(edin_squ_raw$board_size)
# check test situation
unique(edin_squ_raw$test_situation) %in% unique(sample$test_situation)
# check session
unique(edin_squ_raw$session)
# check block
unique(edin_squ_raw$block)
# check trial
unique(edin_squ_raw$trial)
# check pick
unique(edin_squ_raw$pick)
# check hiding locations
unique(edin_squ_raw$hiding_location) %in% unique(sample$hiding_location)
# check correct
unique(edin_squ_raw$correct)

# change data file
edin_squ <- edin_squ_raw %>%
  filter(!is.na(pick))
```


```{r LRC capuchins}

lrc_cap_raw <- read_excel("../data/raw_data/ManyPrimates Pilot_LRC_ACCI.xlsx", 6)
# check column names
names(sample) %in%  names(lrc_cap_raw)
# check condition names
unique(sample$condition) %in%  unique(lrc_cap_raw$condition)

# check species
unique(lrc_cap_raw$species)
 # check subject
unique(lrc_cap_raw$subject_site)
# check age
unique(lrc_cap_raw$age)
# check cup distance
unique(lrc_cap_raw$cup_distance)
# check task experience
unique(lrc_cap_raw$task_experience) %in% unique(sample$task_experience)
# check board size
unique(lrc_cap_raw$board_size)
# check test situation
unique(lrc_cap_raw$test_situation) %in% unique(sample$test_situation)
# check session
unique(lrc_cap_raw$session)
# check block
unique(lrc_cap_raw$block)
# check trial
unique(lrc_cap_raw$trial)
# check pick
unique(lrc_cap_raw$pick)
# check hiding locations
unique(lrc_cap_raw$hiding_location) %in% unique(sample$hiding_location)
# check correct
unique(lrc_cap_raw$correct)

# change data file
lrc_cap <- lrc_cap_raw %>%
  mutate(species = "brown_capuchin_monkey",
         age = ifelse(age == "Unknown (~40)", "40", age),
         cup_distance = gsub("cm","",cup_distance),
         board_size = 56)%>%
  filter(!is.na(pick))%>%
  mutate(session = as.numeric(session),
         cup_distance = as.numeric(cup_distance),
         age = as.numeric(age))
```


```{r ACCI bonobos}

acci_bono_raw <- read_excel("../data/raw_data/ManyPrimates Pilot_LRC_ACCI.xlsx", 7)
# check column names
names(sample) %in%  names(acci_bono_raw)
# check condition names
unique(sample$condition) %in%  unique(acci_bono_raw$condition)

# check species
unique(acci_bono_raw$species)
 # check subject
unique(acci_bono_raw$subject_site)
# check age
unique(acci_bono_raw$age)
# check cup distance
unique(acci_bono_raw$cup_distance)
# check task experience
unique(acci_bono_raw$task_experience) %in% unique(sample$task_experience)
# check board size
unique(acci_bono_raw$board_size)
# check test situation
unique(acci_bono_raw$test_situation) %in% unique(sample$test_situation)
# check session
unique(acci_bono_raw$session)
# check block
unique(acci_bono_raw$block)
# check trial
unique(acci_bono_raw$trial)
# check pick
unique(acci_bono_raw$pick)
# check hiding locations
unique(acci_bono_raw$hiding_location) %in% unique(sample$hiding_location)
# check correct
unique(acci_bono_raw$correct)

# change data file
acci_bono<- acci_bono_raw %>%
  mutate(board_size = 50.8)%>%
  filter(!is.na(pick))%>%
  mutate(session = as.numeric(session),
         cup_distance = as.numeric(cup_distance),
         age = as.numeric(age))

```


```{r edin chimps}

edin_chimps_raw <- read_excel("../data/raw_data/ManyPrimates Pilot Coding_edin_chimps_prel.xlsx", 1)
# check column names
names(sample) %in%  names(edin_chimps_raw)
# check condition names
unique(sample$condition) %in%  unique(edin_chimps_raw$condition)

# check species
unique(edin_chimps_raw$species)
 # check subject
unique(edin_chimps_raw$subject_site)
# check age
unique(edin_chimps_raw$age)
# check cup distance
unique(edin_chimps_raw$cup_distance)
# check task experience
unique(edin_chimps_raw$task_experience) %in% unique(sample$task_experience)
# check board size
unique(edin_chimps_raw$board_size)
# check test situation
unique(edin_chimps_raw$test_situation) %in% unique(sample$test_situation)
# check session
unique(edin_chimps_raw$session)
# check block
unique(edin_chimps_raw$block)
# check trial
unique(edin_chimps_raw$trial)
# check pick
unique(edin_chimps_raw$pick)
# check hiding locations
unique(edin_chimps_raw$hiding_location) %in% unique(sample$hiding_location)
# check correct
unique(edin_chimps_raw$correct)

# change data file
edin_chimps<- edin_chimps_raw %>%
  filter(!is.na(pick))%>%
  mutate(session = as.numeric(session),
         cup_distance = 18.5,
         board_size = 64,
         age = as.numeric(age),
         correct = ifelse(hiding_location == pick, 1,0),
         researcher = "call")%>%
  group_by(subject_site)%>%
  mutate(trial = 1:length(pick)) # to make trial a continous variable)
```



```{r leipzig orangs and chimps}

lpz_orang_chimps_raw <- read_excel("../data/raw_data/ManyPrimates Pilot_Lpz_Mkyhv_data.xlsx", 5)
# check column names
names(sample) %in%  names(lpz_orang_chimps_raw)
# check condition names
unique(sample$condition) %in%  unique(lpz_orang_chimps_raw$condition)

# check species
unique(lpz_orang_chimps_raw$species)
 # check subject
unique(lpz_orang_chimps_raw$subject_site)
# check age
unique(lpz_orang_chimps_raw$age)
# check cup distance
unique(lpz_orang_chimps_raw$cup_distance)
# check task experience
unique(lpz_orang_chimps_raw$task_experience) %in% unique(sample$task_experience)
# check board size
unique(lpz_orang_chimps_raw$board_size)
# check test situation
unique(lpz_orang_chimps_raw$test_situation) %in% unique(sample$test_situation)
# check session
unique(lpz_orang_chimps_raw$session)
# check block
unique(lpz_orang_chimps_raw$block)
# check trial
unique(lpz_orang_chimps_raw$trial)
# check pick
unique(lpz_orang_chimps_raw$pick)
# check hiding locations
unique(lpz_orang_chimps_raw$hiding_location) %in% unique(sample$hiding_location)
# check correct
unique(lpz_orang_chimps_raw$correct)

# change data file
lpz_orang_chimps<- lpz_orang_chimps_raw %>%
  filter(!is.na(pick))%>%
  mutate(session = as.numeric(session))%>%
  group_by(subject_site)%>%
  mutate(trial = 1:length(pick)) # to make trial a continous variable)
```



```{r monkey haven}

mkyhv_mcqs_raw <- read_excel("../data/raw_data/ManyPrimates Pilot_Lpz_Mkyhv_data.xlsx", 8 )
# check column names
names(sample) %in%  names(mkyhv_mcqs_raw)
# check condition names
unique(sample$condition) %in%  unique(mkyhv_mcqs_raw$condition)

# check species
unique(mkyhv_mcqs_raw$species)
 # check subject
unique(mkyhv_mcqs_raw$subject_site)
# check age
unique(mkyhv_mcqs_raw$age)
# check cup distance
unique(mkyhv_mcqs_raw$cup_distance)
# check task experience
unique(mkyhv_mcqs_raw$task_experience) %in% unique(sample$task_experience)
# check board size
unique(mkyhv_mcqs_raw$board_size)
# check test situation
unique(mkyhv_mcqs_raw$test_situation) %in% unique(sample$test_situation)
# check session
unique(mkyhv_mcqs_raw$session)
# check block
unique(mkyhv_mcqs_raw$block)
# check trial
unique(mkyhv_mcqs_raw$trial)
# check pick
unique(mkyhv_mcqs_raw$pick)
# check hiding locations
unique(mkyhv_mcqs_raw$hiding_location) %in% unique(sample$hiding_location)
# check correct
unique(mkyhv_mcqs_raw$correct)

# change data file
mkyhv_mcqs<- mkyhv_mcqs_raw %>%
  mutate(session = as.numeric(session),
         pick = as.numeric(pick),
         correct = as.numeric(correct),
         species = gsub(" ","_",species),
         test_situation = ifelse(test_situation == "double", "group",test_situation),
         secondary_pick = as.character(secondary_pick))%>%
filter(!is.na(pick))

```



```{r merge data files}
raw_data <-bind_rows(
  kuma,
  kris,
  edin_cap,
  edin_squ,
  swee_1,
  swee_2,
  dpz_lem,
  dpz_mac,
  lrc_cap,
  linc,
  acci_bono,
  edin_chimps,
  lpz_orang_chimps,
  mkyhv_mcqs
)%>%
  mutate_at(c("condition","species","subject_site","task_experience","test_situation","hiding_location"),funs(factor(.)))%>%
              select(-comment,-X__1)
```

```{r add life expectancy}
## adding life expectancy and normalizing it

raw_data <- raw_data %>% 
  mutate(life_expectancy = case_when(species == "chimpanzee" ~ 59.4,
                                     species == "ring_tailed_lemur" ~ 37.3,
                                     species == "bonobo"~ 55,
                                     species == "gorilla"~ 60.1,
                                     species == "black_and_white_ruffed_lemur"~ 39.4,
                                     species == "brown_capuchin_monkey" ~ 46,
                                     species == "black_faced_spider_monkey" ~ 46,
                                     species == "long_tailed_macaque" ~ 39,
                                     species == "squirrel_monkey"~ 30.2,
                                     species == "orangutan"~ 59,
                                     species == "barbary_macaque"~ 29.1,
                                     species == "rhesus_macaque"~ 40),
  norm_age = scale(age/life_expectancy, scale = TRUE, center = TRUE))
  
```

```{r quality checks}
raw_data%>%
  ungroup()%>%
  summarise(n = length(unique(subject_site)))

raw_data%>%
  group_by(site,species)%>%
  summarise(n = length(unique(subject_site)))

length(unique(raw_data$site))

# are there subjects with same trial number multiple times?
raw_data%>%
  group_by(site,species,subject_site, trial)%>%
  summarise(n = length(trial))%>%
  filter(n > 1)

```

```{r write data file}
write.csv(raw_data, file="../data/merged_data/01_manyprimates_pilot_merged_data.csv")
```



