---
title: "ManyPrimates plots"
author: "Manuel Bohn"
date: "4 7 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(langcog)

# langcog package is installed by running
# install.packages("devtools")
# devtools::install_github("langcog/langcog")

```

```{r loading data, include = FALSE}
mp_data <- read_csv(file = "../data/merged_data/01_manyprimates_pilot_merged_data.csv")
```

```{r overview by species, echo = FALSE}
plot_individual <- mp_data %>%
   group_by(species,condition,subject_site) %>%
   summarise(correct = mean(correct))

plot_group <- plot_individual %>%
   multi_boot_standard(col = "correct")

ggplot() +
  geom_jitter(data = plot_individual, aes(x = condition, y = correct, col = condition),width = .3,height = .015, alpha = .5)+
  geom_pointrange(data = plot_group, aes(x = condition, y = mean, col = condition,ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 1/3, lty=2)+
  labs(x="",y="proportion dorrect")+
  facet_grid(species ~ . ,switch = "y") +
  theme_few() + 
  ylim(-0.05,1.05)+
  guides(alpha = F)+
  theme(axis.text.y=element_blank(),axis.ticks.y=element_blank(),strip.text.y = element_text(angle = 180))+
  scale_colour_solarized(name="delay")+
  coord_flip()
```

```{r plotting age, echo = FALSE}

plot_age <- mp_data %>%
   group_by(subject_site,norm_age,species,condition) %>%
   summarise(correct = mean(correct))


ggplot(plot_age, 
       aes(x = norm_age, y = correct))+
  geom_point(aes(colour=species))+
  geom_smooth(method = "lm", se = F , level = 0.95)+
  guides(fill=FALSE)+
  geom_hline(yintercept = 1/3, lty=2)+
  facet_grid( ~ condition)+
  theme_few()
```

